# Generated by Django 3.0.8 on 2021-01-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'ordering': ['course__id', 'index']},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='course',
            order_with_respect_to='teacher',
        ),
        migrations.AlterOrderWithRespectTo(
            name='coursetime',
            order_with_respect_to='course',
        ),
        migrations.AlterOrderWithRespectTo(
            name='enrollment',
            order_with_respect_to='user',
        ),
        migrations.AlterOrderWithRespectTo(
            name='record',
            order_with_respect_to='enrollment',
        ),
        migrations.AlterOrderWithRespectTo(
            name='relatedlocation',
            order_with_respect_to='teacher',
        ),
    ]
