# Generated by Django 3.0.8 on 2021-01-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetime',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
