# Generated by Django 3.0.8 on 2021-01-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
