# Generated by Django 3.0.8 on 2020-12-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', 'Customer'), ('T', 'Teacher'), ('S', 'Staff')], max_length=1),
        ),
    ]
