# Generated by Django 3.0.8 on 2021-01-02 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201230_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetime',
            old_name='valid',
            new_name='taken',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 3, 13)),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 1, 2)),
        ),
    ]
