# Generated by Django 3.0.8 on 2020-12-21 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201220_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetime',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursetime',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 1, 18)),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 12, 21)),
        ),
    ]
