# Generated by Django 3.0.8 on 2020-12-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201213_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', 'Customer'), ('T', 'Teacher'), ('S', 'Staff')], default='C', max_length=1),
        ),
    ]
