# Generated by Django 3.0.8 on 2021-01-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210108_1851'),
        ('api', '0002_auto_20210108_1956'),
    ]

    operations = [
    ]
