# Generated by Django 3.0.8 on 2021-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20210109_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='mdeia'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='mdeia'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
