# Generated by Django 3.0.8 on 2020-12-24 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201223_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 3, 4)),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 12, 24)),
        ),
    ]
