# Generated by Django 3.0.8 on 2021-01-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210112_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['teacher__id']},
        ),
        migrations.AlterModelOptions(
            name='coursetime',
            options={'ordering': ['course__id']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['user__id']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['count']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['enrollment__id']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='course',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='coursetime',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='enrollment',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='record',
            order_with_respect_to=None,
        ),
    ]
