# Generated by Django 3.0.8 on 2020-12-25 03:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201224_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='nickname',
            field=models.CharField(default='nickname', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursetime',
            name='day',
            field=models.PositiveIntegerField(choices=[(0, 'mon'), (1, 'tue'), (2, 'wed'), (3, 'thu'), (4, 'fri'), (5, 'sat'), (6, 'sun')]),
        ),
        migrations.AlterField(
            model_name='coursetime',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_time', to='api.Enrollment'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 3, 5)),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='lesson_day',
            field=models.PositiveIntegerField(choices=[(0, 'mon'), (1, 'tue'), (2, 'wed'), (3, 'thu'), (4, 'fri'), (5, 'sat'), (6, 'sun')]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 12, 25)),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField(choices=[(1, 'beginner'), (2, 'intermediate'), (3, 'advanced')])),
                ('note', models.TextField()),
                ('completed', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
